source $HOME/.config/nvim/rc/init_plugins.vim
source $HOME/.config/nvim/rc/general.vim
source $HOME/.config/nvim/rc/windows.vim
source $HOME/.config/nvim/rc/tab_pages.vim
source $HOME/.config/nvim/rc/movement.vim
source $HOME/.config/nvim/rc/searching.vim
source $HOME/.config/nvim/rc/editing.vim
source $HOME/.config/nvim/rc/indentation.vim
source $HOME/.config/nvim/rc/tags.vim
source $HOME/.config/nvim/rc/command_line_window.vim
source $HOME/.config/nvim/rc/plugin_customization.vim
